#!/bin/bash

set -e

if [ "$1" = configure ]; then

	INITSYS=$(ls -al /proc/1/exe | awk -F' ' '{print $NF}' | awk -F'/' '{print $NF}')
	ln -f -s /usr/share/m2ydesk/m2ydesk /usr/bin/m2ydesk

	if [ "systemd" == "$INITSYS" ]; then

		if [ -e /etc/systemd/system/m2ydesk.service ]; then
			rm /etc/systemd/system/m2ydesk.service /usr/lib/systemd/system/m2ydesk.service /usr/lib/systemd/user/m2ydesk.service >/dev/null  2>&1
		fi
		mkdir -p /usr/lib/systemd/system/
		cp /usr/share/m2ydesk/files/systemd/m2ydesk.service /usr/lib/systemd/system/m2ydesk.service
		# try fix error in Ubuntu 18.04
		# Failed to reload m2ydesk.service: Unit m2ydesk.service is not loaded properly: Exec format error.
		# /usr/lib/systemd/system/m2ydesk.service:10: Executable path is not absolute: pkill -f "m2ydesk --"
		if [ -e /usr/bin/pkill ]; then
			sed -i "s|pkill|/usr/bin/pkill|g" /usr/lib/systemd/system/m2ydesk.service
		fi
		systemctl daemon-reload
		systemctl enable m2ydesk
		systemctl start m2ydesk
	fi
fi
